import {
  BACKGROUND_COLOR,
  BACKGROUND_DARK_COLOR,
  DEFAULT_TEXT_COLOR,
  MOVIE_TEXT_COLOR,
  MOVIE_TEXT_DARK_COLOR,
  MOVIE_TITLE_COLOR,
  MOVIE_TITLE_DARK_COLOR,
  TITLE_COLOR,
  TITLE_DARK_COLOR,
  WHITE_COLOR,
} from './colors';

export const darkTheme = {
  title: TITLE_DARK_COLOR,
  movieTitle: MOVIE_TITLE_DARK_COLOR,
  movieText: MOVIE_TEXT_DARK_COLOR,
  backgroundColor: BACKGROUND_DARK_COLOR,
  text: WHITE_COLOR,
};

export const lightTheme = {
  title: TITLE_COLOR,
  movieTitle: MOVIE_TITLE_COLOR,
  movieText: MOVIE_TEXT_COLOR,
  backgroundColor: BACKGROUND_COLOR,
  text: DEFAULT_TEXT_COLOR,
};
